-----------CURSOR-----------------

SET SERVEROUTP ON
DECLARE
CURSOR EMPID IS
SELECT E_ID FROM TCS_EMP;
S NUMBER(2);
BEGIN       
OPEN EMPID;
     LOOP
      FETCH EMPID INTO  S;
      EXIT WHEN EMPID%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(S||'  -  '||EMPID%ROWCOUNT);
      END LOOP;
CLOSE EMPID;
END;
SELECT * FROM TCS_EMP
SELECT * FROM V$OPEN_CURSOR
SELECT * FROM V$PARAMETER WHERE NAME LIKE '%OPEN_CURSORS%';
SELECT COUNT(E_ID) FROM TCS_EMP

------PARAMETRISE CURSOR------

DECLARE
CURSOR EMPID(MNAME VARCHAR2) IS
SELECT E_ID FROM TCS_EMP WHERE M_NAME=MNAME;
S NUMBER(2);
BEGIN 
DBMS_OUTPUT.PUT_LINE('MIDDLE NAME PRAKASH');
OPEN EMPID('PRAKASH');
     LOOP
      FETCH EMPID INTO  S;
      EXIT WHEN EMPID%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(S||'  -  '||EMPID%ROWCOUNT);
      END LOOP;
CLOSE EMPID;
DBMS_OUTPUT.PUT_LINE('MIDDLE NAME KAMLAKAR');

OPEN EMPID('KAMLAKAR');
     LOOP
      FETCH EMPID INTO  S;
      EXIT WHEN EMPID%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE(S||'  -  '||EMPID%ROWCOUNT);
      END LOOP;
CLOSE EMPID;
END;




----------RE-USED CURSOR  IN FOR IN THIS FEACH OPEN CLOSE PERFORM BY FOR CURSOR -----------

DECLARE
CURSOR EMPID(MNAME VARCHAR2) IS
SELECT E_ID FROM TCS_EMP WHERE M_NAME=MNAME;
S NUMBER(2);
BEGIN 
DBMS_OUTPUT.PUT_LINE('MIDDLE NAME PRAKASH');
    FOR I IN  EMPID('PRAKASH')
     LOOP
     DBMS_OUTPUT.PUT_LINE(I.E_ID);
      END LOOP;
DBMS_OUTPUT.PUT_LINE('MIDDLE NAME KAMLAKAR');
FOR I IN EMPID('KAMLAKAR')
LOOP
DBMS_OUTPUT.PUT_LINE(I.E_ID);
      END LOOP;
END;




-------------------ref_curso--------------------
SET SERVEROUTPUT ON
DECLARE
TYPE  DEP_EMP IS REF CURSOR;
      DE_RF DEP_EMP;
      E_NUMBER NUMBER(10);
      D_NUMBER NUMBER(10);
      P_NUMBER NUMBER(10);
BEGIN
     OPEN DE_RF  FOR SELECT E_ID FROM TCS_EMP;
                DBMS_OUTPUT.PUT_LINE('---EMP IDS------');
     LOOP
         FETCH DE_RF INTO E_NUMBER;
         EXIT WHEN DE_RF%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE(E_NUMBER);
    END LOOP;
    CLOSE DE_RF;
         OPEN DE_RF  FOR SELECT D_ID FROM TCS_DEPARTMENT;
                DBMS_OUTPUT.PUT_LINE('---DEPARTMENT IDS------');

     LOOP
         FETCH DE_RF INTO D_NUMBER;
         EXIT WHEN DE_RF%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE(D_NUMBER);
    END LOOP;
    CLOSE DE_RF;
    OPEN DE_RF FOR SELECT PROJECT_ID FROM TCS_PROJECTS;
                DBMS_OUTPUT.PUT_LINE('---PROJECT IDS------');
    LOOP
        FETCH DE_RF INTO P_NUMBER;
        EXIT WHEN DE_RF%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(P_NUMBER);
    END LOOP;
    CLOSE DE_RF;
END;


---------STRONGLY TYPE  REF CORSOR (RETURN)------------



DECLARE 
          RETURN   TCS_PROJECTS%ROWTYPE;
            PCR   SYS_REFCURSOR;                    ----------INSTANT OF  REF NAME IS CURSOR USED (NAME SYS_REFCURSOR)---------------
            PNAME   TCS_PROJECTS%ROWTYPE;
            
BEGIN
     OPEN PCR FOR SELECT * FROM TCS_PROJECTS;
     LOOP
         FETCH PCR INTO PNAME;
         EXIT WHEN PCR%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE(PNAME.PROJECT_NAME);
    END LOOP;
    CLOSE PCR;
END;
     




--------UPDATE CLAUSE IN  CURSOR----------


SET SERVEROUTPUT ON
DECLARE 
       CURSOR SALARY_DEP IS SELECT EMP_ID FROM TCS_DEPARTMENT WHERE D_ID=30 FOR UPDATE;  -----(FOR UPDATE) USED SO NO BODY CAN PERFORM DML OPRATION TILL CURSOR GET EXECUTED----
       D_SALARY NUMBER(8);

BEGIN 
      OPEN SALARY_DEP;
      LOOP
      FETCH SALARY_DEP INTO D_SALARY;  -------FETCHING (EMP_ID) FROM (D_ID=10) AND INSERTING INTO D_SALARY VARIABLE-------
      EXIT WHEN SALARY_DEP%NOTFOUND;
      
      
      UPDATE TCS_DEPARTMENT SET SALARY=45000 WHERE EMP_ID=D_SALARY; ------NOW WE UPDATING SALARY=45000 OF THOSE EMPLOYEEE WHO PRESENT IN (D_SALARY) (I.E  EMPLOYEE FROM DEPARTMENT 10)
      DBMS_OUTPUT.PUT_LINE('ROW AFFECTED'||SQL%ROWCOUNT );
      END LOOP;
      CLOSE SALARY_DEP;
END;
       
SELECT * FROM TCS_DEPARTMENT










